### ISSUE TITLE
script to modify the statistics of the pokes and the IVs

### ISSUE THREAD

**Issue by nichan200** [PokeRogueMOD/JsPoRoMOD#1]
I don't know if it is possible, there will be a script to modify the statistics of the pokes and the IVs, etc.

**Comment by M6D6M6A** [comment]
Oh, sry did not see the issue :( Yea the features are all planned but i had a lot to do the last days, so i hopefully have time later or tomorrow but im not sure, stay tuned.

**Comment by M6D6M6A** [comment]
Ty, for the patience, most features are supported now, if there are still problems, please open a new issue :)
